/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.pom.sanduoclieu;

import static org.testng.Assert.assertTrue;

import org.testng.annotations.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        AssertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

	private void AssertTrue(String string, boolean someLibraryMethod) {
		// TODO Auto-generated method stub
		
	}
}
